version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - "./frontend/src:/app/src:delegated"

  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    ports:
      - "8080:8080"